---
git:
  branch: main
triggers:
  cron: "@daily"
clean_workspace: true
builders:
  - docker
docker_name: drive/jupyter-custom
docker_tags:
  - "latest"
  - "lab-4.0.10-sunet1"
docker_no_cache: true
