#!/bin/bash
rmdir --ignore-fail-on-non-empty /home/jovyan/work
workdir='/home/jovyan'
server="https://sunet.drive.test.sunet.se"
function ncsync {
  mkdir -p ${workdir}
  while true; do
    nextcloudcmd -s --user ${JUPYTERHUB_USER} --password ${NEXTCLOUD_ACCESS_TOKEN} --path / "${workdir}" "${server}"
    sleep 5s
  done
}
ncsync &
